### ISSUE TITLE
YamlのEntity設定の中にMappingが間違えてます（RecommendProduct.dcm.yml）

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/Recommend-plugin#18]
ec-cube 3.0.12
プラグイン：Recommend　1.0.3

問題：YamlのEntity設定の中にMappingが間違えてます
ファイル：
　app/Plugin/Recommend/Resource/doctrine/Plugin.Recommend.Entity.RecommendProduct.dcm.yml

対応方法：
行目：33~
```yaml
    manyToOne:
        Product:
            targetEntity: Eccube\Entity\Product
            inversedBy: RecommendProduct
            joinColumn:
                name: product_id
                referencedColumnName: product_id
    lifecycleCallbacks: {  }
```
↓
```yaml
    manyToOne:
        Product:
            targetEntity: Eccube\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: product_id
    lifecycleCallbacks: {  }
```
